name: seaweedsight
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - opencv
  - matplotlib
  - seaborn
  - statsmodels
  - tqdm
  - pillow
  - requests
